//  Copyright 2026-Present Couchbase, Inc.
//
//  Use of this software is governed by the Business Source License included
//  in the file licenses/BSL-Couchbase.txt.  As of the Change Date specified
//  in that file, in accordance with the Business Source License, use of this
//  software will be governed by the Apache License, Version 2.0, included in
//  the file licenses/APL2.txt.

package algebra

import (
	"encoding/json"
	"strings"

	"github.com/couchbase/query/auth"
	"github.com/couchbase/query/errors"
	"github.com/couchbase/query/expression"
	"github.com/couchbase/query/value"
)

/*
Represents both forms of the CREATE KNOWLEDGE ddl statement:

	CREATE [OR REPLACE] KNOWLEDGE <name> FOR <keyspace> AS <value>
	CREATE [OR REPLACE] KNOWLEDGE FOR <keyspace> FROM <object>

Both associate free-form pieces of natural-language context ("knowledge") with a keyspace, for
later use as ontology/domain hints (e.g. in USING AI queries). The AS form adds a single named
entry; the FROM form (bulk, see Bulk()) adds one entry per field of an object literal in a single
write, with the field name as the knowledge name.

Without OR REPLACE, either form fails if a name it's writing already exists for the keyspace
(there is no ALTER/DROP-then-CREATE KNOWLEDGE - use OR REPLACE instead). With OR REPLACE, an
existing entry's value is overwritten rather than rejected. See Replace().

value is kept as an expression.Expression rather than a plain string/object, so it is exposed via
Expressions()/MapExpressions() and gets picked up by the same generic literal-redaction pass
(sanitizer.SanitizeStatement) used for every other statement, instead of leaking verbatim into
completed_requests/audit logs. Semantics restricts its shape (see semantics.VisitCreateKnowledge);
it is evaluated against the request's arguments at execution time (see execution.CreateKnowledge),
not folded here.
*/
type CreateKnowledge struct {
	statementBase

	name     string                `json:"name"`
	keyspace *Path                 `json:"keyspace"`
	value    expression.Expression `json:"value"`
	bulk     bool                  `json:"bulk"`
	replace  bool                  `json:"replace"`
}

func NewCreateKnowledge(name string, keyspace *Path, value expression.Expression, replace bool) *CreateKnowledge {
	rv := newCreateKnowledge(keyspace, value)
	rv.name = name
	rv.replace = replace
	return rv
}

// NewCreateKnowledgeBulk represents the CREATE KNOWLEDGE FOR <keyspace> FROM <object> form: value
// is expected (and restricted by semantics) to be an object literal or a named/positional
// parameter evaluating to one, with each field becoming its own named knowledge entry. name is
// meaningless for this form (entry names come from value's fields) and is carried only so
// semantics can reject a name given alongside FROM; it is never used to name an entry.
func NewCreateKnowledgeBulk(name string, keyspace *Path, value expression.Expression, replace bool) *CreateKnowledge {
	rv := newCreateKnowledge(keyspace, value)
	rv.name = name
	rv.bulk = true
	rv.replace = replace
	return rv
}

func newCreateKnowledge(keyspace *Path, value expression.Expression) *CreateKnowledge {
	// a bare bucket name (no scope/collection given) implicitly means bucket._default._default
	if keyspace != nil && keyspace.Scope() == "" {
		keyspace = NewPathLong(keyspace.Namespace(), keyspace.Bucket(), "_default", "_default")
	}

	rv := &CreateKnowledge{
		keyspace: keyspace,
		value:    value,
	}

	rv.stmt = rv
	return rv
}

func (this *CreateKnowledge) Accept(visitor Visitor) (interface{}, error) {
	return visitor.VisitCreateKnowledge(this)
}

func (this *CreateKnowledge) Signature() value.Value {
	return nil
}

func (this *CreateKnowledge) Formalize() error {
	return nil
}

func (this *CreateKnowledge) MapExpressions(mapper expression.Mapper) (err error) {
	this.value, err = mapper.Map(this.value)
	return
}

func (this *CreateKnowledge) Expressions() expression.Expressions {
	return expression.Expressions{this.value}
}

func (this *CreateKnowledge) Privileges() (*auth.Privileges, errors.Error) {
	privs := auth.NewPrivileges()
	privs.Add("", auth.PRIV_ADMIN, auth.PRIV_PROPS_NONE)
	return privs, nil
}

func (this *CreateKnowledge) Name() string {
	return this.name
}

// SetName fills in an implicit name (generated by the planner, mirroring PREPARE's opt_name)
// when the statement was written without one.
func (this *CreateKnowledge) SetName(name string) {
	this.name = name
}

func (this *CreateKnowledge) Keyspace() *Path {
	return this.keyspace
}

func (this *CreateKnowledge) Value() expression.Expression {
	return this.value
}

// Bulk reports whether this is the FROM <object> form (one entry per object field, in a single
// write) rather than the AS <value> form (a single named entry).
func (this *CreateKnowledge) Bulk() bool {
	return this.bulk
}

// Replace reports whether OR REPLACE was specified: an existing entry with a name being written is
// overwritten instead of causing the statement to fail.
func (this *CreateKnowledge) Replace() bool {
	return this.replace
}

func (this *CreateKnowledge) MarshalName(m map[string]interface{}) {
	m["namespace"] = this.keyspace.Namespace()
	m["bucket"] = this.keyspace.Bucket()
	m["scope"] = this.keyspace.Scope()
	m["keyspace"] = this.keyspace.Keyspace()
	m["know_name"] = this.name
	m["bulk"] = this.bulk
	m["replace"] = this.replace
}

func (this *CreateKnowledge) MarshalJSON() ([]byte, error) {
	r := map[string]interface{}{"type": "createKnowledge"}
	this.MarshalName(r)
	r["value"] = this.value
	return json.Marshal(r)
}

func (this *CreateKnowledge) Type() string {
	return "CREATE_KNOWLEDGE"
}

func (this *CreateKnowledge) String() string {
	var s strings.Builder
	s.WriteString("CREATE ")
	if this.replace {
		s.WriteString("OR REPLACE ")
	}
	s.WriteString("KNOWLEDGE ")
	if this.bulk {
		s.WriteString("FOR ")
		s.WriteString(this.keyspace.ProtectedString())
		s.WriteString(" FROM ")
		s.WriteString(this.value.String())
		return s.String()
	}
	s.WriteString("`")
	s.WriteString(this.name)
	s.WriteString("` FOR ")
	s.WriteString(this.keyspace.ProtectedString())
	s.WriteString(" AS ")
	s.WriteString(this.value.String())
	return s.String()
}
