//  Copyright 2024-Present Couchbase, Inc.
//
//  Use of this software is governed by the Business Source License included
//  in the file licenses/BSL-Couchbase.txt.  As of the Change Date specified
//  in that file, in accordance with the Business Source License, use of this
//  software will be governed by the Apache License, Version 2.0, included in
//  the file licenses/APL2.txt.

package planshape

const (
	NUL = byte(iota)
	PRIMARYSCAN
	PRIMARYSCAN3
	INDEXSCAN
	INDEXSCAN2
	INDEXSCAN3
	KEYSCAN
	VALUESCAN
	DUMMYSCAN
	COUNTSCAN
	INDEXCOUNTSCAN
	INDEXCOUNTSCAN2
	INDEXCOUNTDISTINCTSCAN2
	DISTINCTSCAN
	UNIONSCAN
	INTERSECTSCAN
	ORDEREDINTERSECTSCAN
	EXPRESSIONSCAN
	INDEXFTSSEARCH
	FETCH
	DUMMYFETCH
	JOIN
	INDEXJOIN
	NEST
	INDEXNEST
	UNNEST
	NLJOIN
	NLNEST
	HASHJOIN
	HASHNEST
	LET
	WITH
	FILTER
	INITIALGROUP
	INTERMEDIATEGROUP
	FINALGROUP
	WINDOWAGGREGATE
	INITIALPROJECT
	INDEXCOUNTPROJECT
	DISTINCT
	ALL
	UNIONALL
	INTERSECT
	INTERSECTALL
	EXCEPT
	EXCEPTALL
	ORDER
	OFFSET
	LIMIT
	SENDINSERT
	SENDUPSERT
	SENDDELETE
	CLONE
	SET
	UNSET
	SENDUPDATE
	MERGE
	ALIAS
	//AUTHORIZE - don't include this operator
	PARALLEL
	SEQUENCE
	DISCARD
	STREAM
	COLLECT
	RECEIVE
	CHANNEL
	CREATEPRIMARYINDEX
	CREATEINDEX
	DROPINDEX
	ALTERINDEX
	BUILDINDEXES
	CREATESCOPE
	DROPSCOPE
	CREATECOLLECTION
	DROPCOLLECTION
	FLUSHCOLLECTION
	GRANTROLE
	REVOKEROLE
	EXPLAIN
	EXPLAINFUNCTION
	PREPARE
	INFERKEYSPACE
	INFEREXPRESSION
	CREATEFUNCTION
	DROPFUNCTION
	EXECUTEFUNCTION
	INDEXADVICE
	ADVISE
	UPDATESTATISTICS
	STARTTRANSACTION
	COMMITTRANSACTION
	ROLLBACKTRANSACTION
	TRANSACTIONISOLATION
	SAVEPOINT
	CREATESEQUENCE
	DROPSEQUENCE
	ALTERSEQUENCE
	CREATEBUCKET
	DROPBUCKET
	ALTERBUCKET
	CREATEGROUP
	DROPGROUP
	ALTERGROUP
	CREATEUSER
	DROPUSER
	ALTERUSER
)

const (
	IDX_OFFSET = 1 << iota
	IDX_LIMIT
	IDX_GROUP
	IDX_COVER
	IDX_ORDER
)
