/****************
 *  n1ql ddl    *
 ****************/

/*
 *  ddl
 */

ddl-stmt ::= index-stmt

index-stmt ::= create-index | drop-index | alter-index


/*
 *  index
 */

create-index ::= 'CREATE' 'INDEX' identifier 'ON' (pool-name ':')? bucket-name '(' subpath (',' subpath)* ')' partition? using?

partition ::= 'PARTITION' 'BY' subpath (',' subpath)*

using ::= 'USING' 'VIEW'

drop-index ::= 'DROP' 'INDEX' (pool-name ':')? bucket-name '.' identifier

alter-index ::= 'ALTER' 'INDEX' (pool-name ':')? bucket-name '.' identifier 'RENAME' 'TO' identifier
